sudo: required
services:
  - docker

before_install:
  - docker build -t jfgf11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jfgf11/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  regiion: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-138495683406"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"